### ISSUE TITLE
image to complete uv map with smplitex

### ISSUE THREAD

**Issue by zhenzhiwang** [dancasas/SMPLitex#2]
Hi,
Thanks for sharing your great work!

I notice that the scripts in readme has only text2image.py and inpaint.py. It seems that if I want to estimate complete uv map from a single image, I need to first use other methods to extract incomplete uv map and mask. Is it right?  I want to know is there any existing pipeline to estimate incomplete uv map from a single image and then make the uv map complete with smplitex? Just like the teaser figure in your repo shows, from a human image to a complete uv map. Looking forward to your reply!
<img width="962" alt="Screenshot 2024-01-02 at 12 34 21" src="https://github.com/dancasas/SMPLitex/assets/26179848/bdb1b798-fccd-44b3-b0e1-9f82879675ff">

**Comment by dancasas** [comment]
Hi, yes we are still working on releasing the script to project image pixels into incomplete texturemap. It basically runs densepose on the input image and uses the IUV predictions to populate the texturemap using the original pixel values. I will try to push the script in the next few days.

**Comment by StGorazd** [comment]
Hi, I am also interested in this step of pipeline do you have any update on it?

**Comment by dancasas** [comment]
Hi, I'm working on releasing the script to create the partial texturemaps, will be released in few days.

**Comment by dancasas** [comment]
Hello @StGorazd and @zhenzhiwang , I've updated the repository with the scripts to create the partial texturemap from image, and the inpainting with Automatic1111.

https://github.com/dancasas/SMPLitex?tab=readme-ov-file#smpl-texture-estimation-from-single-image

Please, check it out and let me know. Thanks!
