### ISSUE TITLE
Better results

### ISSUE THREAD

**Issue by StGorazd** [dancasas/SMPLitex#4]
Hi,
first of all, thank you for the great work.

I want to ask for advice on how to achieve better results. I tried to run the texture generation example from the incomplete sample texture provided, but I'm getting pretty poor results compared to the examples in the paper. Do you have any advice on how to improve the quality or any idea what the problem might be?

There is output I get running the example. I tried different input parameters but do not manage to get rid of black line in the middle of persons face. 
![texture](https://github.com/dancasas/SMPLitex/assets/78076203/4a1278f6-cf27-426c-b122-1bd7b817a92d)
![front_render](https://github.com/dancasas/SMPLitex/assets/78076203/989aac10-9c75-4405-9473-31fc1879b4a3)

Output from text2texture part looks great.

Thank you in advance for answer.

**Comment by dancasas** [comment]
Hi, there are a few things
(1) To get rid of the black pixels,  we compute a tight silhouette and apply some shrinking before projecting the pixels to the UV. This is to make sure no background pixels are projected from the image to the partial texturemap. I will upload a script soon to do this.
(2) For inpainting, I usually get better results with the A1111 approach, not the diffusers. I will also upload some script to run A1111 from Python, but you could play a little with the web interface meanwhile. 
(3) After inpaiting, I usually do an extra img2img step with very low noise factor. This basically fixes a lot of artifacts, but produces a texture that is slightly different than the original subject. If the noise parameter is very low, usually the identity is well kept.

I will try to upload a script that does (1), (2), and (3) exactly how I do in the results from the paper.

**Comment by dancasas** [comment]
Hello @StGorazd I've updated the repository with the scripts to create the partial texturemap from image, and the inpainting with Automatic1111.

https://github.com/dancasas/SMPLitex?tab=readme-ov-file#smpl-texture-estimation-from-single-image

Please, check it out and let me know. Thanks!

**Comment by StGorazd** [comment]
Hi @dancasas ,
thank you for notifying me. I am currently trying to run it, but I ran into some problems. I followed the provided tutorial; however, for some reason, I am getting a different dense pose, which subsequently causes issues while generating the partial texture. I attempted to fix it myself but have not been successful so far.  Do you have any advice or suggestions?

Here is the debug output:
![MEN-Jackets_Vests-id_00003336-09_1_front_debug](https://github.com/dancasas/SMPLitex/assets/78076203/ea6d26e0-cf26-4b84-b412-167dc7e006e5)

**Comment by dancasas** [comment]
@StGorazd you are right! I [just committed](https://github.com/dancasas/SMPLitex/commit/cb0bfff1e0f41c981635937e2b32f4e33a68f380) a fix for this, there was an issue with the DensePose IUV ids. Now it should be fixed, could you update and re-run it?

**Comment by StGorazd** [comment]
Thank you for your prompt response. I have re-run it, and the results are significantly improved.

![MEN-Jackets_Vests-id_00003336-09_1_front_debug](https://github.com/dancasas/SMPLitex/assets/78076203/2390c30c-4023-4b83-8ea1-74a555810110)

Tomorrow, I will try using inpaint part. I will let you know if I encounter any problems.
Thank you for your excellent work.
