### ISSUE TITLE
requirements.txt is broken!

### ISSUE THREAD

**Issue by RohaanA** [dancasas/SMPLitex#5]
Hi,

I wanted to try this model out to generate textures for a tennis player. However the requirements file seems to be broken. More specifically the pytorch line doesn't lead anywhere.

pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git@2f11ddc5ee7d6bd56f2fb6744a16776fab6536f7

It would be better to specify a specific version of pytorch 3d instead I suppose.
Also I wanted to ask what is the recommended python version for this?

**Comment by dancasas** [comment]
For some reason they removed that specific commit, yes. I'd just do a regular installation via 

`pip install "git+https://github.com/facebookresearch/pytorch3d.git"`

As for the Python version, I don't recall any specific requirement. In my env I was using 3.10 (apologies I cannot check this at the moment)

**Comment by RohaanA** [comment]
For now I fixed it by using conda 

> For some reason they removed that specific commit, yes. I'd just do a regular installation via
> 
> `pip install "git+https://github.com/facebookresearch/pytorch3d.git"`
> 
> As for the Python version, I don't recall any specific requirement. In my env I was using 3.10 (apologies I cannot check this at the moment)

Hey, thanks for the quick reply. Yes I was able to resolve it by simply installing pytorch using conda. Also the program worked fine for me using Python 3.9

Anyway, another question I had from you was how I could improve the "finishing" of the result. 

Like in this case the output is not bad but there are some visual glitches in the texturemap. Do I need to fix them manually?

<img width="1280" alt="image" src="https://github.com/dancasas/SMPLitex/assets/75722072/55d0a453-4e81-4898-b27d-e717e84a35eb">

**Comment by dancasas** [comment]
One trick is to use the img2img capability in Automatic1111. Load the SMPLitex ckpt in Automatic1111, then go to img2img tab, load your current SMPLitex texture in the UI, and play with the parameters (noise, steps, guidance, prompt, etc.). With a bit of trial and error you will likely get the desired output. Note that you can also draw masks to improve just certain areas.

Let me know how it goes!
