### ISSUE TITLE
About animation

### ISSUE THREAD

**Issue by stephan000** [dancasas/SMPLitex#6]
Can you tell me how to make an animation like the one in your demo video?

**Comment by dancasas** [comment]
You can create animations by rendering the SMPL meshes in different poses. You can see an example of articulating the SMPL mesh below, where we change the pose parameters 47 and 50 to create an A-pose.

https://github.com/dancasas/SMPLitex/blob/0476822a8273f96ee8ab3463560d6968c46697c7/scripts/render_results.py#L27-L35

To load animations, you can download the [AMASS dataset](https://amass.is.tue.mpg.de), which provides animations in SMPL pose parameters in `npz` format.
