### ISSUE TITLE
There are some differences in the results？

### ISSUE THREAD

**Issue by zjxcc** [dancasas/SMPLitex#7]
Hello, I followed the steps and got the following results. Can you give me some suggestions?
Thank you for your reply！

![截屏2024-07-03 15 15 29](https://github.com/dancasas/SMPLitex/assets/68536773/8a9e909b-caae-4cc2-a2cc-b3bfaaf1cba4)
![截屏2024-07-03 15 15 07](https://github.com/dancasas/SMPLitex/assets/68536773/0f26a43f-610a-4982-a585-5c66bbbb8cc7)

**Comment by dancasas** [comment]
You will get better results using the script https://github.com/dancasas/SMPLitex/blob/main/scripts/inpaint_with_A1111.py, as [explained in the README](https://github.com/dancasas/SMPLitex?tab=readme-ov-file#inpaint-with-automatic1111-best-results). This script will erode the mask, perform inpainting, and them an img2img step to smooth out the results. You can do the same via web interface (as you are doing), but requires multiple iterations.

**Comment by zjxcc** [comment]
I got the result I wanted. I ignored the UV mask map and restored the face. Thanks for sharing such a great project.

**Comment by dancasas** [comment]
Glad it worked! Feel free to share the results! :)

**Comment by zjxcc** [comment]
This is what I got from using the web client, and I understand your inpaint script better.
![截屏2024-07-03 17 10 48](https://github.com/dancasas/SMPLitex/assets/68536773/e1cddbc0-c1cc-4f85-8dd1-b7d8e7546998)

**Comment by dancasas** [comment]
That doesn't look too bad!

**Comment by zjxcc** [comment]
Yes, I wonder if you have any other suggestions?

**Comment by dancasas** [comment]
Play with the noise parameter of the img2img should give you different results. Also, following the parameters used in the script detailed in the README should give you the same results reported in the paper https://github.com/dancasas/SMPLitex?tab=readme-ov-file#inpaint-with-automatic1111-best-results :)

**Comment by zjxcc** [comment]
Ok,I will try it.
